---
author:
  - name: Jane Analyst
    affiliation: Prestigious University
    address: >
      13 Ivy Lane
      Collegeville, USA
    email: Jane@FancySchool.com
    url: http://www.fancySchool.com
  - name: Joe Postdoc
    affiliation: Slightly less prestigious school
title:
  formatted: "Was Ty Cobb a better hitter than Babe Ruth?"
  plain:     "Was Ty Cobb a better hitter than Babe Ruth?"
abstract: >
  We use Bayesian analysis to establish the likelihood that one batter was better than another.
keywords:
  formatted: [Sabermetrics, Cobb, Ruth]
  plain:     [sabermetrics, cobb, ruth]
preamble: >
  \usepackage{amsmath}
output: rticles::jss_article
---

```{r results = 'hide', echo = FALSE, message = FALSE}
library(Lahman)
library(dplyr)
library(ggplot2)


data(Batting)
data(Master)

Master <- Master %>% 
  select(playerID, nameFirst, nameLast) 

Batting <- Batting %>% 
  filter(playerID %in% c('cobbty01', 'ruthba01')) %>% 
  merge(Master, all.x=TRUE) %>% 
  group_by(nameFirst, nameLast) %>% 
  summarise(Hits = sum(H)
            , AtBats = sum(AB)) %>% 
  ungroup() %>% 
  mutate(Name = paste(nameFirst, nameLast)
         , Misses = AtBats - Hits
         , BattingAverage = Hits / AtBats) %>% 
  select(-nameFirst, -nameLast)
```

Did Ty Cobb hit better than the Babe? Let's use Bayesian analysis to try and find out!

The graph below is a posterior density of each player's batting average using an uninformed beta prior density.

```{r echo = FALSE}

dfBeta <- data.frame(x = seq(0, 1, length.out = 1000))

for (i in seq_len(nrow(Batting))){
  dfBeta[, Batting$Name[i]] <- dbeta(dfBeta$x, Batting$Hits[i] + 1, Batting$Misses[i] + 1)
}

dfBeta <- dfBeta %>% 
  tidyr::gather("Batter", "Density", -x)

plt <- ggplot(dfBeta, aes(x = x, y = Density, color = Batter)) + geom_line()
plt
```

Looks like Ty Cobb was a better hitter.